# Generated by Django 6.0.2 on 2026-03-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_scheme_category_alter_eligibilityrule_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='description_mr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
